"""fix_table_test

Revision ID: a2000befb620
Revises: 832efdf7d82e
Create Date: 2025-07-24 19:46:07.589340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2000befb620'
down_revision: Union[str, Sequence[str], None] = '832efdf7d82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('tests', 'name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('tests', 'id')
    # ### end Alembic commands ###
