"""Change_type_data

Revision ID: fbcfaf2a371b
Revises: ad038094adf9
Create Date: 2025-07-24 22:16:22.311953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcfaf2a371b'
down_revision: Union[str, Sequence[str], None] = 'ad038094adf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audios', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('audios', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('components', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('components', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_logging_memorys', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('data_logging_memorys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('development_boards', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('development_boards', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('displays', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('displays', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('e_textiles_craftings', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('e_textiles_craftings', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gps_gnsss', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('gps_gnsss', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('iot_wireless', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('iot_wireless', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kits', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('kits', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('robotics', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('robotics', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sensors', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensors', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tools', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tools', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tools', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensors', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sensors', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('robotics', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('robotics', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('kits', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kits', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('iot_wireless', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('iot_wireless', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('gps_gnsss', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gps_gnsss', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('e_textiles_craftings', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('e_textiles_craftings', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('displays', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('displays', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('development_boards', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('development_boards', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('data_logging_memorys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_logging_memorys', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('components', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('components', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('audios', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audios', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
